# ex 21
# fail-safe job
# We'll define 4 stages - build, test, deploy, clean
# Here, test stage job will be made to fail
# But we'll add "allow_failure" as true in test_job.
# The pipeline will proceed even if test_job fails.
# But we'll define deploy_stage job as manual.
# So, the pipeline will proceed but the manual job won't be executed and we can execute it later whenever we want.

stages:
  - build
  - test
  - deploy
  - clean

build_job:
  stage: build
  script:
    - echo "Build stage job."

test_job:
  stage: test
  allow_failure: true
  script:
    - echo "Test stage job which will fail."
    - exit 1

deploy_job:
  stage: deploy
  when: manual
  script:
    - echo "Deploy stage job."

clean_job:
  stage: clean
  script:
    - echo "Clean stage job."
